/**
 * The layer rail.
 *
 * Transit data is a static JSON file on the CDN — metro lines, metro stations,
 * railway stations and bus stops, regenerated by python/tools/build_transit_data.py.
 * Drawing it costs nothing per view, which is why it is not a live API.
 *
 * AQI and the heatmap are the two layers that do hit the network, so both are
 * debounced and both go through the cached endpoints in api.js.
 */
import { state, viewport } from "./map.js";
import { fetchAqi, fetchListingPoints } from "./api.js";
import { createMarker, poiElement } from "./markers.js";
import { DEFAULTS } from "./config.js";
import { debounce } from "./format.js";
import { toast } from "./toast.js";

const layers = {
  metro:     { polylines: [], markers: [], loaded: false },
  train:     { markers: [] },
  bus:       { markers: [] },
  heatmap:   { instance: null },
  aqi:       { circle: null, label: null, listener: null },
  satellite: {},
};

let transitData = null;

async function loadTransit() {
  if (transitData) return transitData;
  const res = await fetch("./data/transit.json");
  if (!res.ok) throw new Error("Transit data is unavailable.");
  transitData = await res.json();
  return transitData;
}

// ── metro / train / bus ───────────────────────────────────────────────
async function toggleMetro(on) {
  const layer = layers.metro;
  if (!on) {
    layer.polylines.forEach((p) => p.setMap(null));
    layer.markers.forEach((m) => m.setMap(null));
    layer.polylines = []; layer.markers = [];
    return;
  }

  const data = await loadTransit();

  layer.polylines = (data.metro_lines || []).map((line) =>
    new state.maps.Polyline({
      path: line.path,
      strokeColor: line.color,
      strokeOpacity: 0.85,
      strokeWeight: 4,
      map: state.map,
      zIndex: 2,
    }));

  layer.markers = (data.metro_stations || []).map((station) => {
    const marker = createMarker(state.maps, station, poiElement("Ⓜ", `${station.name} metro station`), { pane: "overlayLayer" });
    marker.setMap(state.map);
    return marker;
  });
}

function toggleStops(key, glyph, dataKey, suffix) {
  return async (on) => {
    const layer = layers[key];
    if (!on) {
      layer.markers.forEach((m) => m.setMap(null));
      layer.markers = [];
      return;
    }
    const data = await loadTransit();
    // Bus stops are dense; only draw what is in view, and only when zoomed in
    // enough for them to mean anything.
    const view = viewport();
    const inView = (data[dataKey] || []).filter((p) =>
      p.lat <= view.bounds.north && p.lat >= view.bounds.south &&
      p.lng <= view.bounds.east && p.lng >= view.bounds.west);

    layer.markers = inView.slice(0, 400).map((point) => {
      const marker = createMarker(state.maps, point, poiElement(glyph, `${point.name} ${suffix}`), { pane: "overlayLayer" });
      marker.setMap(state.map);
      return marker;
    });

    if (inView.length > 400) toast(`Showing 400 of ${inView.length} stops. Zoom in for the rest.`);
  };
}

// ── satellite ─────────────────────────────────────────────────────────
function toggleSatellite(on) {
  state.map.setMapTypeId(on ? state.maps.MapTypeId.HYBRID : state.maps.MapTypeId.ROADMAP);
}

// ── heatmap ───────────────────────────────────────────────────────────
async function toggleHeatmap(on) {
  if (!on) {
    layers.heatmap.instance?.setMap(null);
    layers.heatmap.instance = null;
    return;
  }

  const { HeatmapLayer } = await google.maps.importLibrary("visualization");
  const view = viewport();
  const points = await fetchListingPoints(view.bounds);

  // Weight by price so the heat shows where the expensive supply is, not just
  // where any supply is. Sale prices are excluded — they would swamp the scale.
  const data = points
    .filter((p) => Number(p.price) < 500000)
    .map((p) => ({
      location: new state.maps.LatLng(p.lat, p.lng),
      weight: Math.min(3, Math.max(0.4, Number(p.price) / 30000)),
    }));

  layers.heatmap.instance = new HeatmapLayer({
    data,
    map: state.map,
    radius: 38,
    opacity: 0.55,
    gradient: [
      "rgba(15,111,92,0)", "rgba(15,111,92,0.35)", "rgba(15,111,92,0.6)",
      "rgba(200,122,36,0.7)", "rgba(180,71,47,0.85)",
    ],
  });
}

// ── AQI ───────────────────────────────────────────────────────────────
const AQI_BANDS = [
  { max: 50,  color: "#3F9F5B", label: "Good" },
  { max: 100, color: "#C8A82B", label: "Moderate" },
  { max: 150, color: "#C87A24", label: "Poor for sensitive groups" },
  { max: 200, color: "#B4472F", label: "Poor" },
  { max: 300, color: "#8C3A6B", label: "Very poor" },
  { max: Infinity, color: "#6B2F2F", label: "Severe" },
];

const band = (aqi) => AQI_BANDS.find((b) => aqi <= b.max);

async function paintAqi() {
  const view = viewport();
  if (!view) return;
  try {
    const reading = await fetchAqi(view.center.lat, view.center.lng);
    if (!reading?.aqi) return;

    const { color, label } = band(Number(reading.aqi));
    layers.aqi.circle?.setMap(null);
    layers.aqi.circle = new state.maps.Circle({
      center: view.center,
      radius: 2200,
      map: state.map,
      strokeColor: color, strokeOpacity: 0.5, strokeWeight: 1,
      fillColor: color, fillOpacity: 0.16,
      clickable: false, zIndex: 1,
    });

    layers.aqi.label?.setMap(null);
    const el = poiElement(String(reading.aqi), `Air quality index ${reading.aqi} — ${label}`);
    el.style.cssText += `font-family:var(--mono);font-weight:600;font-size:13px;color:${color};padding:6px 9px;border-radius:999px`;
    layers.aqi.label = createMarker(state.maps, view.center, el);
    layers.aqi.label.setMap(state.map);
  } catch (err) {
    console.error("aqi failed", err);
  }
}

const paintAqiDebounced = debounce(paintAqi, DEFAULTS.aqiDebounceMs);

function toggleAqi(on) {
  if (!on) {
    layers.aqi.circle?.setMap(null);
    layers.aqi.label?.setMap(null);
    layers.aqi.circle = layers.aqi.label = null;
    if (layers.aqi.listener) {
      state.maps.event.removeListener(layers.aqi.listener);
      layers.aqi.listener = null;
    }
    return;
  }
  paintAqi();
  layers.aqi.listener = state.map.addListener("idle", paintAqiDebounced);
}

// ── wiring ────────────────────────────────────────────────────────────
const HANDLERS = {
  metro: toggleMetro,
  train: toggleStops("train", "🚉", "train_stations", "railway station"),
  bus: toggleStops("bus", "🚏", "bus_stops", "bus stop"),
  satellite: toggleSatellite,
  heatmap: toggleHeatmap,
  aqi: toggleAqi,
};

export function initControls(rail) {
  rail.addEventListener("click", async (event) => {
    const button = event.target.closest("[data-layer]");
    if (!button) return;

    const layer = button.dataset.layer;
    const next = button.getAttribute("aria-pressed") !== "true";
    button.setAttribute("aria-pressed", String(next));
    button.disabled = true;

    try {
      await HANDLERS[layer](next);
    } catch (err) {
      console.error(`${layer} layer failed`, err);
      button.setAttribute("aria-pressed", "false");
      toast(err.message || "That layer could not load.", "bad");
    } finally {
      button.disabled = false;
    }
  });

  // Redraw viewport-bounded stop layers as the map moves.
  document.addEventListener("markers:drawn", () => {
    ["train", "bus"].forEach((key) => {
      const button = rail.querySelector(`[data-layer="${key}"]`);
      if (button?.getAttribute("aria-pressed") === "true") HANDLERS[key](true);
    });
  });
}
